// Generated by tools/codegen/agent-schemas.ts. Do not edit manually.

/** @typedef {Record<string, unknown>} AgentJsonSchema */

export const agentSchemaCount = 23;
export const agentSchemaFilenames = Object.freeze([
  "ai-validation-input.schema.json",
  "ai-validation-result.schema.json",
  "asset-recommendation-input.schema.json",
  "asset-recommendation-result.schema.json",
  "campaign-analysis-input.schema.json",
  "campaign-analysis-result.schema.json",
  "copy-generation-input.schema.json",
  "copy-generation-result.schema.json",
  "creative-document.schema.json",
  "edit-operation-batch.schema.json",
  "export-assistant-input.schema.json",
  "export-assistant-result.schema.json",
  "export-request.schema.json",
  "export-result.schema.json",
  "layout-plan.schema.json",
  "layout-planning-input.schema.json",
  "natural-language-edit-input.schema.json",
  "product-match-input.schema.json",
  "product-match-result.schema.json",
  "render-request.schema.json",
  "render-result.schema.json",
  "validation-request.schema.json",
  "validation-result.schema.json",
]);

/** @type {Readonly<Record<string, AgentJsonSchema>>} */
export const agentSchemas = Object.freeze({
  "ai-validation-input.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "AI Validation Input",
    type: "object",
    required: [
      "workspaceId",
      "validationRunId",
      "creativeVersionId",
      "renderFileId",
      "brief",
      "product",
      "rules",
    ],
    properties: {
      workspaceId: {
        type: "string",
        format: "uuid",
      },
      validationRunId: {
        type: "string",
        format: "uuid",
      },
      creativeVersionId: {
        type: "string",
        format: "uuid",
      },
      renderFileId: {
        type: "string",
        format: "uuid",
      },
      brief: {
        type: "object",
        additionalProperties: true,
      },
      product: {
        type: ["object", "null"],
        additionalProperties: true,
      },
      landingSnapshot: {
        type: ["object", "null"],
        additionalProperties: true,
      },
      rules: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: true,
        },
      },
    },
    additionalProperties: false,
  },
  "ai-validation-result.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "AI Validation Result",
    type: "object",
    required: ["results"],
    properties: {
      results: {
        type: "array",
        items: {
          type: "object",
          required: [
            "ruleCode",
            "severity",
            "message",
            "confidence",
            "targetElementIds",
            "evidence",
          ],
          properties: {
            ruleCode: {
              type: "string",
              minLength: 1,
            },
            severity: {
              type: "string",
              enum: ["INFO", "WARNING", "ERROR"],
            },
            message: {
              type: "string",
              minLength: 1,
            },
            confidence: {
              type: "number",
              minimum: 0,
              maximum: 1,
            },
            targetElementIds: {
              type: "array",
              items: {
                type: "string",
              },
            },
            evidence: {
              type: "array",
              items: {
                type: "string",
              },
            },
            suggestedFix: {
              type: ["object", "null"],
              additionalProperties: true,
            },
          },
          additionalProperties: false,
        },
      },
    },
    additionalProperties: false,
  },
  "asset-recommendation-input.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Asset Recommendation Input",
    type: "object",
    required: ["workspaceId", "campaignId", "productId", "formatProfile", "brief", "assets"],
    properties: {
      workspaceId: {
        type: "string",
        format: "uuid",
      },
      campaignId: {
        type: "string",
        format: "uuid",
      },
      productId: {
        type: "string",
        format: "uuid",
      },
      formatProfile: {
        type: "object",
        additionalProperties: true,
      },
      brief: {
        type: "object",
        additionalProperties: true,
      },
      assets: {
        type: "array",
        items: {
          type: "object",
          required: ["assetVersionId", "analysis"],
          properties: {
            assetVersionId: {
              type: "string",
              format: "uuid",
            },
            analysis: {
              type: "object",
              additionalProperties: true,
            },
            licenseStatus: {
              type: "string",
              minLength: 1,
            },
          },
          additionalProperties: false,
        },
      },
    },
    additionalProperties: false,
  },
  "asset-recommendation-result.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Asset Recommendation Result",
    type: "object",
    required: ["productId", "rankedAssets"],
    properties: {
      productId: {
        type: "string",
        format: "uuid",
      },
      rankedAssets: {
        type: "array",
        items: {
          type: "object",
          required: ["assetVersionId", "score", "reasons", "risks", "recommendedUsage"],
          properties: {
            assetVersionId: {
              type: "string",
              format: "uuid",
            },
            score: {
              type: "number",
              minimum: 0,
              maximum: 1,
            },
            reasons: {
              type: "array",
              items: {
                type: "string",
              },
            },
            risks: {
              type: "array",
              items: {
                type: "string",
              },
            },
            recommendedUsage: {
              type: "string",
              enum: ["PRIMARY", "SECONDARY", "BACKGROUND", "LOGO", "DO_NOT_USE"],
            },
          },
          additionalProperties: false,
        },
      },
    },
    additionalProperties: false,
  },
  "campaign-analysis-input.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Campaign Analysis Input",
    type: "object",
    required: ["workspaceId", "campaignId", "sourceIds", "brandProfile", "locale"],
    properties: {
      workspaceId: {
        type: "string",
        format: "uuid",
      },
      campaignId: {
        type: "string",
        format: "uuid",
      },
      sourceIds: {
        type: "array",
        minItems: 1,
        items: {
          type: "string",
          format: "uuid",
        },
      },
      brandProfile: {
        type: "object",
        additionalProperties: true,
      },
      existingBrief: {
        type: ["object", "null"],
        additionalProperties: true,
      },
      locale: {
        type: "string",
        const: "ko-KR",
      },
    },
    additionalProperties: false,
  },
  "campaign-analysis-result.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Campaign Analysis Result",
    type: "object",
    required: [
      "objective",
      "targets",
      "benefits",
      "brandMessage",
      "campaignMessages",
      "products",
      "forbiddenExpressions",
      "citations",
      "confidence",
    ],
    properties: {
      objective: {
        type: "string",
        minLength: 1,
      },
      targets: {
        type: "array",
        items: {
          type: "string",
        },
      },
      period: {
        type: ["object", "null"],
        properties: {
          startDate: {
            type: ["string", "null"],
          },
          endDate: {
            type: ["string", "null"],
          },
        },
        additionalProperties: false,
      },
      benefits: {
        type: "array",
        items: {
          type: "string",
        },
      },
      brandMessage: {
        type: ["string", "null"],
      },
      campaignMessages: {
        type: "array",
        items: {
          type: "string",
        },
      },
      products: {
        type: "array",
        items: {
          type: "object",
          required: ["sourceName"],
          properties: {
            sourceName: {
              type: "string",
              minLength: 1,
            },
            context: {
              type: ["string", "null"],
            },
          },
          additionalProperties: false,
        },
      },
      ctaDirection: {
        type: "array",
        items: {
          type: "string",
        },
      },
      forbiddenExpressions: {
        type: "array",
        items: {
          type: "string",
        },
      },
      landingUrl: {
        type: ["string", "null"],
      },
      citations: {
        type: "array",
        items: {
          type: "object",
          required: ["sourceId", "excerptHash"],
          properties: {
            sourceId: {
              type: "string",
              format: "uuid",
            },
            excerptHash: {
              type: "string",
              minLength: 1,
            },
            location: {
              type: ["string", "null"],
            },
          },
          additionalProperties: false,
        },
      },
      confidence: {
        type: "number",
        minimum: 0,
        maximum: 1,
      },
      uncertainties: {
        type: "array",
        items: {
          type: "string",
        },
      },
    },
    additionalProperties: false,
  },
  "copy-generation-input.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Copy Generation Input",
    type: "object",
    required: [
      "workspaceId",
      "campaignId",
      "product",
      "brief",
      "brandProfile",
      "textSlots",
      "variantCount",
    ],
    properties: {
      workspaceId: {
        type: "string",
        format: "uuid",
      },
      campaignId: {
        type: "string",
        format: "uuid",
      },
      product: {
        type: "object",
        additionalProperties: true,
      },
      brief: {
        type: "object",
        additionalProperties: true,
      },
      brandProfile: {
        type: "object",
        additionalProperties: true,
      },
      textSlots: {
        type: "array",
        items: {
          type: "object",
          required: ["code", "maxUnits"],
          properties: {
            code: {
              type: "string",
              minLength: 1,
            },
            maxUnits: {
              type: "integer",
              minimum: 1,
            },
            maxLines: {
              type: ["integer", "null"],
              minimum: 1,
            },
            countMode: {
              type: "string",
            },
          },
          additionalProperties: true,
        },
      },
      variantCount: {
        type: "integer",
        minimum: 1,
        maximum: 10,
      },
    },
    additionalProperties: false,
  },
  "copy-generation-result.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Copy Generation Result",
    type: "object",
    required: ["variants"],
    properties: {
      variants: {
        type: "array",
        minItems: 1,
        items: {
          type: "object",
          required: ["variantId", "slots", "rationale"],
          properties: {
            variantId: {
              type: "string",
              minLength: 1,
            },
            slots: {
              type: "object",
              additionalProperties: {
                type: "string",
              },
            },
            rationale: {
              type: "string",
              minLength: 1,
            },
            riskFlags: {
              type: "array",
              items: {
                type: "string",
              },
            },
          },
          additionalProperties: false,
        },
      },
    },
    additionalProperties: false,
  },
  "creative-document.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Creative Document",
    type: "object",
    required: [
      "schemaVersion",
      "formatProfileId",
      "canvas",
      "elements",
      "usedAssetVersionIds",
      "copyAssets",
      "metadata",
    ],
    properties: {
      schemaVersion: {
        type: "string",
        const: "1.0.0",
      },
      formatProfileId: {
        type: "string",
        format: "uuid",
      },
      layoutTemplateId: {
        type: ["string", "null"],
        format: "uuid",
      },
      canvas: {
        type: "object",
        required: ["width", "height", "colorMode", "transparentBackground"],
        properties: {
          width: {
            type: "integer",
            minimum: 1,
          },
          height: {
            type: "integer",
            minimum: 1,
          },
          colorMode: {
            type: "string",
            enum: ["RGB"],
          },
          transparentBackground: {
            type: "boolean",
          },
          background: {
            type: ["string", "null"],
          },
        },
        additionalProperties: false,
      },
      elements: {
        type: "array",
        items: {
          type: "object",
          required: ["id", "type", "x", "y", "width", "height", "zIndex", "locked", "visible"],
          properties: {
            id: {
              type: "string",
              minLength: 1,
            },
            type: {
              type: "string",
              enum: ["IMAGE", "TEXT", "LOGO", "SHAPE", "GROUP", "CTA", "BACKGROUND"],
            },
            name: {
              type: "string",
            },
            x: {
              type: "number",
            },
            y: {
              type: "number",
            },
            width: {
              type: "number",
              exclusiveMinimum: 0,
            },
            height: {
              type: "number",
              exclusiveMinimum: 0,
            },
            rotation: {
              type: "number",
              default: 0,
            },
            opacity: {
              type: "number",
              minimum: 0,
              maximum: 1,
              default: 1,
            },
            zIndex: {
              type: "integer",
            },
            locked: {
              type: "boolean",
            },
            visible: {
              type: "boolean",
            },
            assetVersionId: {
              type: ["string", "null"],
              format: "uuid",
            },
            textSlotCode: {
              type: ["string", "null"],
            },
            text: {
              type: ["string", "null"],
            },
            style: {
              type: "object",
              additionalProperties: true,
            },
            crop: {
              type: ["object", "null"],
              additionalProperties: true,
            },
            constraints: {
              type: "object",
              additionalProperties: true,
            },
            metadata: {
              type: "object",
              additionalProperties: true,
            },
          },
          additionalProperties: false,
        },
      },
      usedAssetVersionIds: {
        type: "array",
        items: {
          type: "string",
          format: "uuid",
        },
        uniqueItems: true,
      },
      copyAssets: {
        type: "object",
        additionalProperties: {
          type: "string",
        },
      },
      safeZones: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: true,
        },
      },
      metadata: {
        type: "object",
        required: ["workspaceId", "campaignId", "creativeId", "productId"],
        properties: {
          workspaceId: {
            type: "string",
            format: "uuid",
          },
          campaignId: {
            type: "string",
            format: "uuid",
          },
          creativeId: {
            type: "string",
            format: "uuid",
          },
          productId: {
            type: ["string", "null"],
            format: "uuid",
          },
          briefVersionId: {
            type: "string",
            format: "uuid",
          },
          sourceVersionId: {
            type: ["string", "null"],
            format: "uuid",
          },
        },
        additionalProperties: true,
      },
    },
    additionalProperties: false,
  },
  "edit-operation-batch.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Edit Operation Batch",
    type: "object",
    required: ["operations", "summary", "requiresAssetSelection", "requiresUserConfirmation"],
    properties: {
      operations: {
        type: "array",
        minItems: 1,
        items: {
          type: "object",
          required: ["operationId", "action", "targetIds", "payload"],
          properties: {
            operationId: {
              type: "string",
              minLength: 1,
            },
            action: {
              type: "string",
              enum: [
                "MOVE",
                "RESIZE",
                "REPLACE_ASSET",
                "UPDATE_TEXT",
                "CHANGE_STYLE",
                "REORDER",
                "DELETE",
                "ADD",
              ],
            },
            targetIds: {
              type: "array",
              items: {
                type: "string",
              },
              minItems: 1,
            },
            payload: {
              type: "object",
              additionalProperties: true,
            },
            preconditions: {
              type: "array",
              items: {
                type: "object",
                additionalProperties: true,
              },
            },
            explanation: {
              type: "string",
              minLength: 1,
            },
          },
          additionalProperties: false,
        },
      },
      summary: {
        type: "string",
        minLength: 1,
      },
      requiresAssetSelection: {
        type: "boolean",
      },
      assetSelectionOptions: {
        type: "array",
        items: {
          type: "string",
          format: "uuid",
        },
      },
      requiresUserConfirmation: {
        type: "boolean",
      },
      warnings: {
        type: "array",
        items: {
          type: "string",
        },
      },
    },
    additionalProperties: false,
  },
  "export-assistant-input.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Export Assistant Input",
    type: "object",
    required: ["workspaceId", "exportJobId", "campaign", "creativeVersions", "exportRecipe"],
    properties: {
      workspaceId: {
        type: "string",
        format: "uuid",
      },
      exportJobId: {
        type: "string",
        format: "uuid",
      },
      campaign: {
        type: "object",
        additionalProperties: true,
      },
      creativeVersions: {
        type: "array",
        minItems: 1,
        items: {
          type: "object",
          additionalProperties: true,
        },
      },
      exportRecipe: {
        type: "object",
        additionalProperties: true,
      },
    },
    additionalProperties: false,
  },
  "export-assistant-result.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Export Assistant Result",
    type: "object",
    required: ["items", "packageName", "notes"],
    properties: {
      items: {
        type: "array",
        items: {
          type: "object",
          required: ["creativeVersionId", "relativePath", "fileBaseName"],
          properties: {
            creativeVersionId: {
              type: "string",
              format: "uuid",
            },
            relativePath: {
              type: "string",
              minLength: 1,
            },
            fileBaseName: {
              type: "string",
              minLength: 1,
            },
          },
          additionalProperties: false,
        },
      },
      packageName: {
        type: "string",
        minLength: 1,
      },
      notes: {
        type: "array",
        items: {
          type: "string",
        },
      },
    },
    additionalProperties: false,
  },
  "export-request.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Export Request",
    type: "object",
    required: ["exportJobId", "workspaceId", "campaignId", "exportRecipe", "items", "options"],
    properties: {
      exportJobId: {
        type: "string",
        format: "uuid",
      },
      workspaceId: {
        type: "string",
        format: "uuid",
      },
      campaignId: {
        type: "string",
        format: "uuid",
      },
      exportRecipe: {
        type: "object",
        additionalProperties: true,
      },
      items: {
        type: "array",
        minItems: 1,
        items: {
          type: "object",
          required: [
            "creativeVersionId",
            "approvalRequestId",
            "validationRunId",
            "creativeDocument",
          ],
          properties: {
            creativeVersionId: {
              type: "string",
              format: "uuid",
            },
            approvalRequestId: {
              type: "string",
              format: "uuid",
            },
            validationRunId: {
              type: "string",
              format: "uuid",
            },
            creativeDocument: {
              $ref: "creative-document.schema.json",
            },
            relativePath: {
              type: "string",
              minLength: 1,
            },
          },
          additionalProperties: true,
        },
      },
      options: {
        type: "object",
        additionalProperties: true,
      },
    },
    additionalProperties: false,
  },
  "export-result.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Export Result",
    type: "object",
    required: ["exportJobId", "status", "files", "manifest", "warnings"],
    properties: {
      exportJobId: {
        type: "string",
        format: "uuid",
      },
      status: {
        type: "string",
        enum: ["COMPLETED", "PARTIAL_SUCCESS", "FAILED"],
      },
      files: {
        type: "array",
        items: {
          type: "object",
          required: ["fileId", "relativePath", "role", "bytes", "checksumSha256"],
          properties: {
            fileId: {
              type: "string",
              format: "uuid",
            },
            relativePath: {
              type: "string",
              minLength: 1,
            },
            role: {
              type: "string",
              enum: ["CREATIVE", "MANIFEST", "VALIDATION_REPORT", "COPY_CSV", "PACKAGE"],
            },
            bytes: {
              type: "integer",
              minimum: 0,
            },
            checksumSha256: {
              type: "string",
              minLength: 1,
            },
          },
          additionalProperties: false,
        },
      },
      manifest: {
        type: "object",
        additionalProperties: true,
      },
      warnings: {
        type: "array",
        items: {
          type: "string",
        },
      },
      error: {
        type: ["object", "null"],
        additionalProperties: true,
      },
    },
    additionalProperties: false,
  },
  "layout-plan.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Layout Plan",
    type: "object",
    required: [
      "formatProfileId",
      "templateId",
      "elements",
      "usedAssetVersionIds",
      "copyAssets",
      "rationale",
    ],
    properties: {
      formatProfileId: {
        type: "string",
        format: "uuid",
      },
      templateId: {
        type: ["string", "null"],
        format: "uuid",
      },
      elements: {
        type: "array",
        minItems: 0,
        items: {
          type: "object",
          required: ["elementId", "elementType", "slotCode", "x", "y", "width", "height", "zIndex"],
          properties: {
            elementId: {
              type: "string",
              minLength: 1,
            },
            elementType: {
              type: "string",
              enum: ["IMAGE", "TEXT", "LOGO", "CTA", "SHAPE", "BACKGROUND"],
            },
            slotCode: {
              type: "string",
              minLength: 1,
            },
            assetVersionId: {
              type: ["string", "null"],
              format: "uuid",
            },
            textValue: {
              type: ["string", "null"],
            },
            x: {
              type: "number",
            },
            y: {
              type: "number",
            },
            width: {
              type: "number",
              exclusiveMinimum: 0,
            },
            height: {
              type: "number",
              exclusiveMinimum: 0,
            },
            zIndex: {
              type: "integer",
            },
            style: {
              type: "object",
              additionalProperties: true,
            },
            constraints: {
              type: "object",
              additionalProperties: true,
            },
          },
          additionalProperties: false,
        },
      },
      usedAssetVersionIds: {
        type: "array",
        items: {
          type: "string",
          format: "uuid",
        },
        uniqueItems: true,
      },
      copyAssets: {
        type: "object",
        additionalProperties: {
          type: "string",
        },
      },
      rationale: {
        type: "string",
        minLength: 1,
      },
      riskFlags: {
        type: "array",
        items: {
          type: "string",
        },
      },
    },
    additionalProperties: false,
  },
  "layout-planning-input.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Layout Planning Input",
    type: "object",
    required: [
      "workspaceId",
      "campaignId",
      "creativeId",
      "productId",
      "formatProfile",
      "template",
      "assets",
      "copyVariant",
    ],
    properties: {
      workspaceId: {
        type: "string",
        format: "uuid",
      },
      campaignId: {
        type: "string",
        format: "uuid",
      },
      creativeId: {
        type: "string",
        format: "uuid",
      },
      productId: {
        type: "string",
        format: "uuid",
      },
      formatProfile: {
        type: "object",
        additionalProperties: true,
      },
      template: {
        type: "object",
        additionalProperties: true,
      },
      assets: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: true,
        },
      },
      copyVariant: {
        type: "object",
        additionalProperties: true,
      },
      brandProfile: {
        type: "object",
        additionalProperties: true,
      },
    },
    additionalProperties: false,
  },
  "natural-language-edit-input.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Natural Language Edit Input",
    type: "object",
    required: ["workspaceId", "creativeVersionId", "commandText", "creativeDocument"],
    properties: {
      workspaceId: {
        type: "string",
        format: "uuid",
      },
      creativeVersionId: {
        type: "string",
        format: "uuid",
      },
      commandText: {
        type: "string",
        minLength: 1,
      },
      creativeDocument: {
        $ref: "creative-document.schema.json",
      },
      latestValidationResults: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: true,
        },
      },
      availableAssets: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: true,
        },
      },
    },
    additionalProperties: false,
  },
  "product-match-input.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Product Match Input",
    type: "object",
    required: [
      "workspaceId",
      "campaignId",
      "briefVersionId",
      "extractedProducts",
      "candidateProducts",
    ],
    properties: {
      workspaceId: {
        type: "string",
        format: "uuid",
      },
      campaignId: {
        type: "string",
        format: "uuid",
      },
      briefVersionId: {
        type: "string",
        format: "uuid",
      },
      extractedProducts: {
        type: "array",
        minItems: 1,
        items: {
          type: "object",
          required: ["sourceName"],
          properties: {
            sourceName: {
              type: "string",
              minLength: 1,
            },
            context: {
              type: ["string", "null"],
            },
          },
          additionalProperties: false,
        },
      },
      candidateProducts: {
        type: "array",
        items: {
          type: "object",
          required: ["productId", "name"],
          properties: {
            productId: {
              type: "string",
              format: "uuid",
            },
            name: {
              type: "string",
              minLength: 1,
            },
            aliases: {
              type: "array",
              items: {
                type: "string",
              },
            },
            attributes: {
              type: "object",
              additionalProperties: true,
            },
          },
          additionalProperties: false,
        },
      },
    },
    additionalProperties: false,
  },
  "product-match-result.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Product Match Result",
    type: "object",
    required: ["matches"],
    properties: {
      matches: {
        type: "array",
        items: {
          type: "object",
          required: ["sourceName", "candidates", "recommendedAction"],
          properties: {
            sourceName: {
              type: "string",
              minLength: 1,
            },
            candidates: {
              type: "array",
              maxItems: 5,
              items: {
                type: "object",
                required: ["productId", "score", "reason"],
                properties: {
                  productId: {
                    type: "string",
                    format: "uuid",
                  },
                  score: {
                    type: "number",
                    minimum: 0,
                    maximum: 1,
                  },
                  reason: {
                    type: "string",
                    minLength: 1,
                  },
                },
                additionalProperties: false,
              },
            },
            recommendedAction: {
              type: "string",
              enum: ["CONFIRM_TOP", "REVIEW", "CREATE_NEW", "EXCLUDE"],
            },
          },
          additionalProperties: false,
        },
      },
    },
    additionalProperties: false,
  },
  "render-request.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Render Request",
    type: "object",
    required: [
      "requestId",
      "workspaceId",
      "creativeVersionId",
      "purpose",
      "creativeDocument",
      "outputProfile",
    ],
    properties: {
      requestId: {
        type: "string",
        format: "uuid",
      },
      workspaceId: {
        type: "string",
        format: "uuid",
      },
      creativeVersionId: {
        type: "string",
        format: "uuid",
      },
      purpose: {
        type: "string",
        enum: ["PREVIEW", "VALIDATION", "FINAL_EXPORT"],
      },
      creativeDocument: {
        $ref: "creative-document.schema.json",
      },
      outputProfile: {
        type: "object",
        required: ["mimeType", "width", "height"],
        properties: {
          mimeType: {
            type: "string",
            enum: ["image/png", "image/jpeg"],
          },
          width: {
            type: "integer",
            minimum: 1,
          },
          height: {
            type: "integer",
            minimum: 1,
          },
          maxBytes: {
            type: ["integer", "null"],
            minimum: 1,
          },
          transparentBackground: {
            type: "boolean",
          },
        },
        additionalProperties: true,
      },
      assetAccess: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: true,
        },
      },
      fontPackageId: {
        type: ["string", "null"],
      },
    },
    additionalProperties: false,
  },
  "render-result.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Render Result",
    type: "object",
    required: [
      "requestId",
      "status",
      "outputFileId",
      "width",
      "height",
      "bytes",
      "checksumSha256",
      "warnings",
    ],
    properties: {
      requestId: {
        type: "string",
        format: "uuid",
      },
      status: {
        type: "string",
        enum: ["COMPLETED", "FAILED"],
      },
      outputFileId: {
        type: ["string", "null"],
        format: "uuid",
      },
      width: {
        type: ["integer", "null"],
      },
      height: {
        type: ["integer", "null"],
      },
      bytes: {
        type: ["integer", "null"],
      },
      checksumSha256: {
        type: ["string", "null"],
      },
      renderMetadata: {
        type: "object",
        additionalProperties: true,
      },
      warnings: {
        type: "array",
        items: {
          type: "string",
        },
      },
      error: {
        type: ["object", "null"],
        additionalProperties: true,
      },
    },
    additionalProperties: false,
  },
  "validation-request.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Validation Request",
    type: "object",
    required: [
      "validationRunId",
      "workspaceId",
      "creativeVersionId",
      "formatSnapshot",
      "ruleSnapshot",
      "creativeDocument",
    ],
    properties: {
      validationRunId: {
        type: "string",
        format: "uuid",
      },
      workspaceId: {
        type: "string",
        format: "uuid",
      },
      creativeVersionId: {
        type: "string",
        format: "uuid",
      },
      formatSnapshot: {
        type: "object",
        additionalProperties: true,
      },
      ruleSnapshot: {
        type: "object",
        additionalProperties: true,
      },
      creativeDocument: {
        $ref: "creative-document.schema.json",
      },
      renderFileId: {
        type: ["string", "null"],
        format: "uuid",
      },
      briefSnapshot: {
        type: "object",
        additionalProperties: true,
      },
      productSnapshot: {
        type: ["object", "null"],
        additionalProperties: true,
      },
    },
    additionalProperties: false,
  },
  "validation-result.schema.json": {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Validation Engine Result",
    type: "object",
    required: ["validationRunId", "status", "summary", "results"],
    properties: {
      validationRunId: {
        type: "string",
        format: "uuid",
      },
      status: {
        type: "string",
        enum: ["PASS", "WARNING", "ERROR", "FAILED"],
      },
      summary: {
        type: "object",
        required: ["errorCount", "warningCount", "infoCount"],
        properties: {
          errorCount: {
            type: "integer",
            minimum: 0,
          },
          warningCount: {
            type: "integer",
            minimum: 0,
          },
          infoCount: {
            type: "integer",
            minimum: 0,
          },
        },
        additionalProperties: false,
      },
      results: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: true,
        },
      },
      engineVersion: {
        type: "string",
        minLength: 1,
      },
      error: {
        type: ["object", "null"],
        additionalProperties: true,
      },
    },
    additionalProperties: false,
  },
});
