/** @typedef {typeof API_ERROR_CODES[number]} ApiErrorCode */

export const API_ERROR_CODES = Object.freeze([
  "INVALID_REQUEST",
  "FIELD_VALIDATION_FAILED",
  "AUTHENTICATION_REQUIRED",
  "SESSION_EXPIRED",
  "CSRF_VALIDATION_FAILED",
  "WORKSPACE_ACCESS_DENIED",
  "ROLE_PERMISSION_DENIED",
  "DOMAIN_POLICY_DENIED",
  "RESOURCE_NOT_FOUND",
  "IDEMPOTENCY_PAYLOAD_CONFLICT",
  "STATE_TRANSITION_CONFLICT",
  "OPEN_APPROVAL_EXISTS",
  "VERSION_SUPERSEDED",
  "REVISION_MISMATCH",
  "UPLOAD_TOO_LARGE",
  "UNSUPPORTED_MEDIA_TYPE",
  "CHECKSUM_MISMATCH",
  "FILE_MAGIC_MISMATCH",
  "BRIEF_NOT_CONFIRMED",
  "PRODUCT_MATCH_INCOMPLETE",
  "ASSET_POOL_INSUFFICIENT",
  "FORMAT_UNAVAILABLE",
  "CREATIVE_VERSION_FROZEN",
  "CREATIVE_DOCUMENT_INVALID",
  "VALIDATION_ERROR_OPEN",
  "WARNING_ACKNOWLEDGEMENT_REQUIRED",
  "APPROVAL_REQUIRED",
  "APPROVAL_VERSION_MISMATCH",
  "ASSET_LICENSE_INVALID",
  "REVALIDATION_REQUIRED",
  "EXPORT_RECIPE_UNAVAILABLE",
  "JOB_NOT_CANCELLABLE",
  "JOB_NOT_RETRYABLE",
  "RATE_LIMIT_EXCEEDED",
  "WORKSPACE_CONCURRENCY_LIMIT",
  "INTERNAL_ERROR",
  "DEPENDENCY_ERROR",
  "SERVICE_UNAVAILABLE",
  "GATEWAY_TIMEOUT",
]);

export const API_ERROR_CATALOG = Object.freeze({
  INVALID_REQUEST: { httpStatus: 400, retryable: false },
  FIELD_VALIDATION_FAILED: { httpStatus: 400, retryable: false },
  AUTHENTICATION_REQUIRED: { httpStatus: 401, retryable: false },
  SESSION_EXPIRED: { httpStatus: 401, retryable: false },
  CSRF_VALIDATION_FAILED: { httpStatus: 403, retryable: false },
  WORKSPACE_ACCESS_DENIED: { httpStatus: 403, retryable: false },
  ROLE_PERMISSION_DENIED: { httpStatus: 403, retryable: false },
  DOMAIN_POLICY_DENIED: { httpStatus: 403, retryable: false },
  RESOURCE_NOT_FOUND: { httpStatus: 404, retryable: false },
  IDEMPOTENCY_PAYLOAD_CONFLICT: { httpStatus: 409, retryable: false },
  STATE_TRANSITION_CONFLICT: { httpStatus: 409, retryable: false },
  OPEN_APPROVAL_EXISTS: { httpStatus: 409, retryable: false },
  VERSION_SUPERSEDED: { httpStatus: 409, retryable: false },
  REVISION_MISMATCH: { httpStatus: 412, retryable: true },
  UPLOAD_TOO_LARGE: { httpStatus: 413, retryable: false },
  UNSUPPORTED_MEDIA_TYPE: { httpStatus: 415, retryable: false },
  CHECKSUM_MISMATCH: { httpStatus: 422, retryable: true },
  FILE_MAGIC_MISMATCH: { httpStatus: 422, retryable: false },
  BRIEF_NOT_CONFIRMED: { httpStatus: 422, retryable: false },
  PRODUCT_MATCH_INCOMPLETE: { httpStatus: 422, retryable: false },
  ASSET_POOL_INSUFFICIENT: { httpStatus: 422, retryable: false },
  FORMAT_UNAVAILABLE: { httpStatus: 422, retryable: false },
  CREATIVE_VERSION_FROZEN: { httpStatus: 422, retryable: false },
  CREATIVE_DOCUMENT_INVALID: { httpStatus: 422, retryable: false },
  VALIDATION_ERROR_OPEN: { httpStatus: 422, retryable: false },
  WARNING_ACKNOWLEDGEMENT_REQUIRED: { httpStatus: 422, retryable: false },
  APPROVAL_REQUIRED: { httpStatus: 422, retryable: false },
  APPROVAL_VERSION_MISMATCH: { httpStatus: 422, retryable: false },
  ASSET_LICENSE_INVALID: { httpStatus: 422, retryable: false },
  REVALIDATION_REQUIRED: { httpStatus: 422, retryable: false },
  EXPORT_RECIPE_UNAVAILABLE: { httpStatus: 422, retryable: false },
  JOB_NOT_CANCELLABLE: { httpStatus: 422, retryable: false },
  JOB_NOT_RETRYABLE: { httpStatus: 422, retryable: false },
  RATE_LIMIT_EXCEEDED: { httpStatus: 429, retryable: true },
  WORKSPACE_CONCURRENCY_LIMIT: { httpStatus: 429, retryable: true },
  INTERNAL_ERROR: { httpStatus: 500, retryable: true },
  DEPENDENCY_ERROR: { httpStatus: 502, retryable: true },
  SERVICE_UNAVAILABLE: { httpStatus: 503, retryable: true },
  GATEWAY_TIMEOUT: { httpStatus: 504, retryable: true },
});

export const API_ERROR_CODE_COUNT = 39;

export function isApiErrorCode(value = "") {
  return API_ERROR_CODES.includes(value);
}
