import { randomUUID } from "node:crypto";

export type CampaignStatus = "DRAFT" | "ACTIVE" | "ARCHIVED" | "COMPLETED";
export type CampaignSourceStatus = "ACTIVE" | "REMOVED";
export type BriefVersionStatus = "DRAFT" | "CONFIRMED" | "INVALIDATED";
export type CampaignProductStatus = "PENDING" | "CONFIRMED" | "REJECTED";
export type SelectionStatus = "RECOMMENDED" | "SELECTED" | "EXCLUDED";
export type GenerationStatus = "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED";

export interface CampaignRecord { readonly id: string; readonly workspaceId: string; readonly brandId: string; readonly displayCode: string; readonly name: string; readonly objectiveCode: string; readonly status: CampaignStatus; readonly currentStep: string; readonly startDate?: string; readonly endDate?: string; readonly landingUrl?: string; readonly ownerUserId?: string; readonly revisionNo: number; readonly createdAt: string; readonly updatedAt: string; }
export interface CampaignActivityRecord { readonly id: string; readonly workspaceId: string; readonly campaignId: string; readonly type: string; readonly payloadJson: Readonly<Record<string, unknown>>; readonly createdAt: string; }
export interface CampaignSourceRecord { readonly id: string; readonly workspaceId: string; readonly campaignId: string; readonly fileObjectId: string; readonly sourceType: string; readonly notes?: string; readonly uploadedBy?: string; readonly status: CampaignSourceStatus; readonly createdAt: string; readonly removedAt?: string; }
export interface CampaignBriefRecord { readonly id: string; readonly workspaceId: string; readonly campaignId: string; readonly currentVersionId?: string; readonly revisionNo: number; }
export interface CampaignBriefVersionRecord { readonly id: string; readonly workspaceId: string; readonly campaignBriefId: string; readonly versionNo: number; readonly parentVersionId?: string; readonly sourceKind: string; readonly contentJson: Readonly<Record<string, unknown>>; readonly sourceCitationsJson: readonly unknown[]; readonly brandProfileSnapshotJson: Readonly<Record<string, unknown>>; readonly status: BriefVersionStatus; readonly createdBy?: string; readonly confirmedAt?: string; readonly createdAt: string; }
export interface ProductMatchingCandidateRecord { readonly id: string; readonly workspaceId: string; readonly campaignId: string; readonly briefVersionId: string; readonly productId: string; readonly score: number; readonly rationale?: string; readonly confirmed: boolean; readonly createdAt: string; }
export interface CampaignProductRecord { readonly id: string; readonly workspaceId: string; readonly campaignId: string; readonly productId: string; readonly briefVersionId: string; readonly status: CampaignProductStatus; readonly confirmedAt?: string; readonly createdAt: string; }
export interface CampaignAssetRecommendationRecord { readonly id: string; readonly workspaceId: string; readonly campaignId: string; readonly productId: string; readonly assetVersionId: string; readonly score: number; readonly rationale?: string; readonly status: SelectionStatus; readonly licenseStatus: string; readonly createdAt: string; readonly updatedAt: string; }
export interface CampaignAssetPoolSelectionRecord { readonly id: string; readonly workspaceId: string; readonly campaignId: string; readonly productId: string; readonly assetVersionId: string; readonly status: SelectionStatus; readonly reason?: string; readonly updatedAt: string; }
export interface CampaignChannelSelectionRecord { readonly id: string; readonly workspaceId: string; readonly campaignId: string; readonly channelCode: string; readonly status: "SELECTED" | "REMOVED"; readonly snapshotJson: Readonly<Record<string, unknown>>; readonly updatedAt: string; }
export interface CampaignFormatSelectionRecord { readonly id: string; readonly workspaceId: string; readonly campaignId: string; readonly channelCode: string; readonly formatProfileId: string; readonly profileVersion: string; readonly status: "SELECTED" | "REMOVED"; readonly snapshotJson: Readonly<Record<string, unknown>>; readonly updatedAt: string; }
export interface GenerationRequestRecord { readonly id: string; readonly workspaceId: string; readonly campaignId: string; readonly briefVersionId: string; readonly status: GenerationStatus; readonly estimatedItemCount: number; readonly createdAt: string; readonly updatedAt: string; }
export interface GenerationItemRecord { readonly id: string; readonly workspaceId: string; readonly generationRequestId: string; readonly productId: string; readonly formatProfileId: string; readonly variantKey: string; readonly status: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED"; readonly checkpointJson: Readonly<Record<string, unknown>>; readonly updatedAt: string; }

export interface CampaignRepositories {
  listCampaigns(workspaceId: string, brandId?: string): Promise<readonly CampaignRecord[]>;
  getCampaign(workspaceId: string, id: string): Promise<CampaignRecord | null>;
  createCampaign(input: Omit<CampaignRecord, "id" | "status" | "revisionNo" | "createdAt" | "updatedAt"> & { id?: string }): Promise<CampaignRecord>;
  updateCampaign(workspaceId: string, id: string, patch: Partial<Pick<CampaignRecord, "brandId" | "name" | "objectiveCode" | "startDate" | "endDate" | "landingUrl" | "ownerUserId" | "currentStep">>, expectedRevision?: number): Promise<CampaignRecord>;
  archiveCampaign(workspaceId: string, id: string, expectedRevision?: number): Promise<CampaignRecord>;
  listActivity(workspaceId: string, campaignId: string): Promise<readonly CampaignActivityRecord[]>;
  addActivity(input: Omit<CampaignActivityRecord, "id" | "createdAt"> & { id?: string; createdAt?: string }): Promise<CampaignActivityRecord>;
  listSources(workspaceId: string, campaignId: string, includeRemoved?: boolean): Promise<readonly CampaignSourceRecord[]>;
  attachSource(input: Omit<CampaignSourceRecord, "id" | "status" | "createdAt"> & { id?: string }): Promise<CampaignSourceRecord>;
  removeSource(workspaceId: string, campaignId: string, sourceId: string): Promise<CampaignSourceRecord>;
  getBrief(workspaceId: string, campaignId: string): Promise<CampaignBriefRecord | null>;
  createBriefVersion(input: Omit<CampaignBriefVersionRecord, "id" | "versionNo" | "status" | "createdAt"> & { id?: string; versionNo?: number; status?: BriefVersionStatus; createdAt?: string }): Promise<CampaignBriefVersionRecord>;
  getBriefVersion(workspaceId: string, versionId: string): Promise<CampaignBriefVersionRecord | null>;
  confirmBriefVersion(workspaceId: string, versionId: string): Promise<CampaignBriefVersionRecord>;
  listMatchingCandidates(workspaceId: string, campaignId: string): Promise<readonly ProductMatchingCandidateRecord[]>;
  addMatchingCandidates(items: readonly (Omit<ProductMatchingCandidateRecord, "id" | "confirmed" | "createdAt"> & { id?: string })[]): Promise<readonly ProductMatchingCandidateRecord[]>;
  listCampaignProducts(workspaceId: string, campaignId: string): Promise<readonly CampaignProductRecord[]>;
  upsertCampaignProduct(input: Omit<CampaignProductRecord, "id" | "createdAt"> & { id?: string; createdAt?: string }): Promise<CampaignProductRecord>;
  listAssetRecommendations(workspaceId: string, campaignId: string, productId?: string): Promise<readonly CampaignAssetRecommendationRecord[]>;
  addAssetRecommendations(items: readonly (Omit<CampaignAssetRecommendationRecord, "id" | "status" | "createdAt" | "updatedAt"> & { id?: string })[]): Promise<readonly CampaignAssetRecommendationRecord[]>;
  listAssetPoolSelections(workspaceId: string, campaignId: string, productId?: string): Promise<readonly CampaignAssetPoolSelectionRecord[]>;
  upsertAssetPoolSelection(input: Omit<CampaignAssetPoolSelectionRecord, "id" | "updatedAt"> & { id?: string }): Promise<CampaignAssetPoolSelectionRecord>;
  listChannelSelections(workspaceId: string, campaignId: string): Promise<readonly CampaignChannelSelectionRecord[]>;
  upsertChannelSelection(input: Omit<CampaignChannelSelectionRecord, "id" | "updatedAt"> & { id?: string }): Promise<CampaignChannelSelectionRecord>;
  listFormatSelections(workspaceId: string, campaignId: string): Promise<readonly CampaignFormatSelectionRecord[]>;
  clearFormatSelections(workspaceId: string, campaignId: string): Promise<void>;
  upsertFormatSelection(input: Omit<CampaignFormatSelectionRecord, "id" | "updatedAt"> & { id?: string }): Promise<CampaignFormatSelectionRecord>;
  createGenerationAggregate(input: Omit<GenerationRequestRecord, "id" | "status" | "createdAt" | "updatedAt"> & { id?: string }, items: readonly (Omit<GenerationItemRecord, "id" | "status" | "updatedAt"> & { id?: string })[]): Promise<{ readonly request: GenerationRequestRecord; readonly items: readonly GenerationItemRecord[] }>;
  getGenerationRequest(workspaceId: string, id: string): Promise<{ readonly request: GenerationRequestRecord; readonly items: readonly GenerationItemRecord[] } | null>;
}

export interface CampaignSeed { readonly campaigns?: readonly CampaignRecord[]; readonly activities?: readonly CampaignActivityRecord[]; readonly sources?: readonly CampaignSourceRecord[]; readonly briefs?: readonly CampaignBriefRecord[]; readonly briefVersions?: readonly CampaignBriefVersionRecord[]; readonly matchingCandidates?: readonly ProductMatchingCandidateRecord[]; readonly campaignProducts?: readonly CampaignProductRecord[]; readonly assetRecommendations?: readonly CampaignAssetRecommendationRecord[]; readonly assetPoolSelections?: readonly CampaignAssetPoolSelectionRecord[]; readonly channelSelections?: readonly CampaignChannelSelectionRecord[]; readonly formatSelections?: readonly CampaignFormatSelectionRecord[]; readonly generationRequests?: readonly GenerationRequestRecord[]; readonly generationItems?: readonly GenerationItemRecord[] }
function notFound(kind: string): Error { const error = new Error(`${kind} not found`); Object.assign(error, { code: "RESOURCE_NOT_FOUND", statusCode: 404 }); return error; }
function revisionMismatch(): Error { const error = new Error("Campaign revision has changed"); Object.assign(error, { code: "REVISION_MISMATCH", statusCode: 412 }); return error; }
const nowIso = (): string => new Date().toISOString();

export function createInMemoryCampaignRepositories(seed: CampaignSeed = {}): CampaignRepositories {
  const campaigns = new Map((seed.campaigns ?? []).map((item) => [item.id, item])); const activities = new Map((seed.activities ?? []).map((item) => [item.id, item])); const sources = new Map((seed.sources ?? []).map((item) => [item.id, item])); const briefs = new Map((seed.briefs ?? []).map((item) => [item.campaignId, item])); const briefVersions = new Map((seed.briefVersions ?? []).map((item) => [item.id, item])); const candidates = new Map((seed.matchingCandidates ?? []).map((item) => [item.id, item])); const products = new Map((seed.campaignProducts ?? []).map((item) => [item.id, item])); const recommendations = new Map((seed.assetRecommendations ?? []).map((item) => [item.id, item])); const pool = new Map((seed.assetPoolSelections ?? []).map((item) => [item.id, item])); const channels = new Map((seed.channelSelections ?? []).map((item) => [item.id, item])); const formats = new Map((seed.formatSelections ?? []).map((item) => [item.id, item])); const generationRequests = new Map((seed.generationRequests ?? []).map((item) => [item.id, item])); const generationItems = new Map((seed.generationItems ?? []).map((item) => [item.id, item]));
  const campaign = (workspaceId: string, id: string): CampaignRecord => { const item = campaigns.get(id); if (!item || item.workspaceId !== workspaceId) throw notFound("Campaign"); return item; };
  const briefForCampaign = (workspaceId: string, campaignId: string): CampaignBriefRecord => { campaign(workspaceId, campaignId); const existing = briefs.get(campaignId); if (existing) return existing; const item = { id: randomUUID(), workspaceId, campaignId, revisionNo: 1 }; briefs.set(campaignId, item); return item; };
  return {
    async listCampaigns(workspaceId, brandId) { return [...campaigns.values()].filter((item) => item.workspaceId === workspaceId && (!brandId || item.brandId === brandId) && item.status !== "ARCHIVED"); },
    async getCampaign(workspaceId, id) { const item = campaigns.get(id); return item?.workspaceId === workspaceId ? item : null; },
    async createCampaign(input) { const createdAt = nowIso(); const item = Object.freeze({ id: input.id ?? randomUUID(), ...input, status: "DRAFT" as const, revisionNo: 1, createdAt, updatedAt: createdAt }); campaigns.set(item.id, item); return item; },
    async updateCampaign(workspaceId, id, patch, expectedRevision) { const current = campaign(workspaceId, id); if (expectedRevision !== undefined && current.revisionNo !== expectedRevision) throw revisionMismatch(); const next = Object.freeze({ ...current, ...patch, revisionNo: current.revisionNo + 1, updatedAt: nowIso() }); campaigns.set(id, next); return next; },
    async archiveCampaign(workspaceId, id, expectedRevision) { const current = campaign(workspaceId, id); if (expectedRevision !== undefined && current.revisionNo !== expectedRevision) throw revisionMismatch(); const next = Object.freeze({ ...current, status: "ARCHIVED" as const, revisionNo: current.revisionNo + 1, updatedAt: nowIso() }); campaigns.set(id, next); return next; },
    async listActivity(workspaceId, campaignId) { campaign(workspaceId, campaignId); return [...activities.values()].filter((item) => item.workspaceId === workspaceId && item.campaignId === campaignId).sort((a, b) => a.createdAt.localeCompare(b.createdAt)); },
    async addActivity(input) { const item = Object.freeze({ id: input.id ?? randomUUID(), ...input, createdAt: input.createdAt ?? nowIso() }); campaign(item.workspaceId, item.campaignId); activities.set(item.id, item); return item; },
    async listSources(workspaceId, campaignId, includeRemoved = false) { campaign(workspaceId, campaignId); return [...sources.values()].filter((item) => item.workspaceId === workspaceId && item.campaignId === campaignId && (includeRemoved || item.status !== "REMOVED")); },
    async attachSource(input) { campaign(input.workspaceId, input.campaignId); const item = Object.freeze({ id: input.id ?? randomUUID(), ...input, status: "ACTIVE" as const, createdAt: nowIso() }); sources.set(item.id, item); return item; },
    async removeSource(workspaceId, campaignId, sourceId) { const current = sources.get(sourceId); if (!current || current.workspaceId !== workspaceId || current.campaignId !== campaignId) throw notFound("Campaign source"); const next = Object.freeze({ ...current, status: "REMOVED" as const, removedAt: nowIso() }); sources.set(sourceId, next); return next; },
    async getBrief(workspaceId, campaignId) { const item = briefs.get(campaignId); return item?.workspaceId === workspaceId ? item : null; },
    async createBriefVersion(input) { const brief = briefForCampaign(input.workspaceId, input.campaignBriefId); const current = [...briefVersions.values()].filter((item) => item.campaignBriefId === brief.id).sort((a, b) => b.versionNo - a.versionNo)[0]; const item = Object.freeze({ id: input.id ?? randomUUID(), ...input, versionNo: input.versionNo ?? (current?.versionNo ?? 0) + 1, status: input.status ?? "DRAFT" as const, sourceCitationsJson: input.sourceCitationsJson ?? [], createdAt: input.createdAt ?? nowIso() }); briefVersions.set(item.id, item); briefs.set(brief.campaignId, Object.freeze({ ...brief, currentVersionId: item.id, revisionNo: brief.revisionNo + 1 })); return item; },
    async getBriefVersion(workspaceId, versionId) { const item = briefVersions.get(versionId); return item?.workspaceId === workspaceId ? item : null; },
    async confirmBriefVersion(workspaceId, versionId) { const current = briefVersions.get(versionId); if (!current || current.workspaceId !== workspaceId) throw notFound("Brief version"); if (current.status === "CONFIRMED") return current; const next = Object.freeze({ ...current, status: "CONFIRMED" as const, confirmedAt: nowIso() }); briefVersions.set(versionId, next); return next; },
    async listMatchingCandidates(workspaceId, campaignId) { campaign(workspaceId, campaignId); return [...candidates.values()].filter((item) => item.workspaceId === workspaceId && item.campaignId === campaignId); },
    async addMatchingCandidates(items) { const created = items.map((input) => Object.freeze({ id: input.id ?? randomUUID(), ...input, confirmed: false, createdAt: nowIso() })); for (const item of created) { campaign(item.workspaceId, item.campaignId); candidates.set(item.id, item); } return created; },
    async listCampaignProducts(workspaceId, campaignId) { campaign(workspaceId, campaignId); return [...products.values()].filter((item) => item.workspaceId === workspaceId && item.campaignId === campaignId); },
    async upsertCampaignProduct(input) { campaign(input.workspaceId, input.campaignId); const existing = [...products.values()].find((item) => item.workspaceId === input.workspaceId && item.campaignId === input.campaignId && item.productId === input.productId); const item = Object.freeze({ id: existing?.id ?? input.id ?? randomUUID(), ...input, createdAt: existing?.createdAt ?? input.createdAt ?? nowIso() }); products.set(item.id, item); return item; },
    async listAssetRecommendations(workspaceId, campaignId, productId) { campaign(workspaceId, campaignId); return [...recommendations.values()].filter((item) => item.workspaceId === workspaceId && item.campaignId === campaignId && (!productId || item.productId === productId)); },
    async addAssetRecommendations(items) { const created = items.map((input) => Object.freeze({ id: input.id ?? randomUUID(), ...input, status: "RECOMMENDED" as const, createdAt: nowIso(), updatedAt: nowIso() })); for (const item of created) { campaign(item.workspaceId, item.campaignId); recommendations.set(item.id, item); } return created; },
    async listAssetPoolSelections(workspaceId, campaignId, productId) { campaign(workspaceId, campaignId); return [...pool.values()].filter((item) => item.workspaceId === workspaceId && item.campaignId === campaignId && (!productId || item.productId === productId)); },
    async upsertAssetPoolSelection(input) { campaign(input.workspaceId, input.campaignId); const existing = [...pool.values()].find((item) => item.workspaceId === input.workspaceId && item.campaignId === input.campaignId && item.productId === input.productId && item.assetVersionId === input.assetVersionId); const item = Object.freeze({ id: existing?.id ?? input.id ?? randomUUID(), ...input, updatedAt: nowIso() }); pool.set(item.id, item); return item; },
    async listChannelSelections(workspaceId, campaignId) { campaign(workspaceId, campaignId); return [...channels.values()].filter((item) => item.workspaceId === workspaceId && item.campaignId === campaignId); },
    async upsertChannelSelection(input) { campaign(input.workspaceId, input.campaignId); const existing = [...channels.values()].find((item) => item.workspaceId === input.workspaceId && item.campaignId === input.campaignId && item.channelCode === input.channelCode); const item = Object.freeze({ id: existing?.id ?? input.id ?? randomUUID(), ...input, updatedAt: nowIso() }); channels.set(item.id, item); return item; },
    async listFormatSelections(workspaceId, campaignId) { campaign(workspaceId, campaignId); return [...formats.values()].filter((item) => item.workspaceId === workspaceId && item.campaignId === campaignId); },
    async clearFormatSelections(workspaceId, campaignId) { campaign(workspaceId, campaignId); for (const [id, item] of formats) if (item.workspaceId === workspaceId && item.campaignId === campaignId) formats.delete(id); },
    async upsertFormatSelection(input) { campaign(input.workspaceId, input.campaignId); const existing = [...formats.values()].find((item) => item.workspaceId === input.workspaceId && item.campaignId === input.campaignId && item.channelCode === input.channelCode && item.formatProfileId === input.formatProfileId); const item = Object.freeze({ id: existing?.id ?? input.id ?? randomUUID(), ...input, updatedAt: nowIso() }); formats.set(item.id, item); return item; },
    async createGenerationAggregate(input, items) { campaign(input.workspaceId, input.campaignId); const createdAt = nowIso(); const request = Object.freeze({ id: input.id ?? randomUUID(), ...input, status: "QUEUED" as const, createdAt, updatedAt: createdAt }); const createdItems = items.map((item) => Object.freeze({ id: item.id ?? randomUUID(), ...item, generationRequestId: request.id, status: "QUEUED" as const, checkpointJson: item.checkpointJson ?? {}, updatedAt: createdAt })); generationRequests.set(request.id, request); for (const item of createdItems) generationItems.set(item.id, item); return { request, items: createdItems }; },
    async getGenerationRequest(workspaceId, id) { const request = generationRequests.get(id); if (!request || request.workspaceId !== workspaceId) return null; return { request, items: [...generationItems.values()].filter((item) => item.workspaceId === workspaceId && item.generationRequestId === id) }; },
  };
}
