import { randomUUID } from "node:crypto";
import type { FastifyPluginAsync } from "fastify";
import { createCatalogAdminUseCases, createVersionedCatalogAdmin, type CatalogAdminUseCases } from "../../../../../packages/core/src/modules/media-catalog/admin-use-cases.js";
import { createInMemoryCatalogRepository } from "../../../../../packages/core/src/modules/media-catalog/repositories.js";
import { etagForRevision, revisionFromEtag } from "../../concurrency/etag.js";
interface Options { readonly admin?: CatalogAdminUseCases }
function body(request: unknown): Record<string, unknown> { return ((request as { body?: unknown }).body ?? {}) as Record<string, unknown>; }
function workspaceId(request: unknown): string { return (request as { params: { workspaceId: string } }).params.workspaceId; }
export const catalogAdminRoutes: FastifyPluginAsync<Options> = async (app, options) => {
  const admin = options.admin ?? createCatalogAdminUseCases(createInMemoryCatalogRepository()); const versions = createVersionedCatalogAdmin();
  app.post("/api/v1/workspaces/:workspaceId/media-catalog.integrity-check", { config: { operationId: "runCatalogIntegrityCheck", roles: ["OWNER", "ADMIN"] } }, async (request, reply) => { const id = randomUUID(); reply.header("Operation-Location", `/api/v1/workspaces/${workspaceId(request)}/jobs/${id}`); return reply.code(202).send({ jobId: id, status: "QUEUED" }); });
  app.post("/api/v1/workspaces/:workspaceId/media-catalog/guideline-versions", { config: { operationId: "createGuidelineVersion", roles: ["OWNER", "ADMIN"] } }, async (request, reply) => reply.code(201).send({ data: versions.create({ stableKey: String(body(request).stableKey), version: String(body(request).version), status: "DRAFT", payload: body(request) }) }));
  app.post("/api/v1/workspaces/:workspaceId/media-catalog/rule-sets", { config: { operationId: "createRuleSet", roles: ["OWNER", "ADMIN"] } }, async (request, reply) => reply.code(201).send({ data: versions.create({ stableKey: String(body(request).stableKey), version: String(body(request).version), status: "DRAFT", payload: body(request) }) }));
  app.post("/api/v1/workspaces/:workspaceId/media-catalog/layout-templates", { config: { operationId: "createLayoutTemplate", roles: ["OWNER", "ADMIN"] } }, async (request, reply) => reply.code(201).send({ data: versions.create({ stableKey: String(body(request).stableKey), version: String(body(request).version), status: "DRAFT", payload: body(request) }) }));
  app.post("/api/v1/workspaces/:workspaceId/media-catalog/export-recipes", { config: { operationId: "createExportRecipe", roles: ["OWNER", "ADMIN"] } }, async (request, reply) => reply.code(201).send({ data: versions.create({ stableKey: String(body(request).stableKey), version: String(body(request).version), status: "DRAFT", payload: body(request) }) }));
  app.post("/api/v1/workspaces/:workspaceId/media-catalog/format-profiles", { config: { operationId: "createFormatProfile", roles: ["OWNER", "ADMIN"] } }, async (request, reply) => { const input = body(request); const profile = await admin.createFormatProfile({ channelId: String(input.channelId), channelCode: String(input.channelCode) as never, stableKey: String(input.stableKey), version: String(input.version), name: String(input.name), status: "DRAFT", renderMode: String(input.renderMode ?? "PLATFORM_COMPOSED"), mediaType: String(input.mediaType ?? "STATIC_IMAGE"), spec: typeof input.spec === "object" && input.spec ? input.spec as Record<string, unknown> : {}, ruleSetId: String(input.ruleSetId ?? ""), exportRecipeId: String(input.exportRecipeId ?? "") }); return reply.code(201).send({ data: profile }); });
  app.patch("/api/v1/workspaces/:workspaceId/media-catalog/format-profiles/:formatProfileId", { config: { operationId: "updateFormatProfileStatus", roles: ["OWNER", "ADMIN"] } }, async (request, reply) => { const input = body(request); const header = (request as { headers?: { "if-match"?: string } }).headers?.["if-match"]; const profile = await admin.updateFormatProfileStatus((request as { params: { formatProfileId: string } }).params.formatProfileId, String(input.status) as never, header ? revisionFromEtag(header) : undefined); reply.header("ETag", etagForRevision(profile.revisionNo)); return { data: profile }; });
};
