import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
const targetPath = join(
  repositoryRoot,
  "packages",
  "contracts",
  "src",
  "agent-schemas",
  "index.ts",
);
const desktop = process.env.USERPROFILE ?? "";
const designRoot =
  process.env.PLUME_DESIGN_ROOT ?? join(desktop, "Desktop", "da-creative-webapp-design");
const schemaDirectory = join(designRoot, "09_agent-engine", "schemas");
const registryPath = join(designRoot, "09_agent-engine", "schema-registry.yaml");

function readUpstreamSchemas() {
  if (!existsSync(schemaDirectory) || !existsSync(registryPath)) {
    return null;
  }
  const registry = readFileSync(registryPath, "utf8");
  const filenames = [...registry.matchAll(/^\s+filename:\s*([^\s]+)\s*$/gm)]
    .map((match) => match[1])
    .sort();
  return Object.fromEntries(
    filenames.map((filename) => [
      filename,
      JSON.parse(readFileSync(join(schemaDirectory, filename), "utf8")),
    ]),
  );
}

function validateSchemaRefs(schemas) {
  const filenames = new Set(Object.keys(schemas));
  for (const [filename, schema] of Object.entries(schemas)) {
    const refs = [];
    const visit = (value) => {
      if (!value || typeof value !== "object") return;
      if (typeof value.$ref === "string") refs.push(value.$ref);
      for (const child of Object.values(value)) visit(child);
    };
    visit(schema);
    for (const ref of refs) {
      const referencedFile = ref.split("#", 1)[0];
      if (referencedFile && !filenames.has(referencedFile)) {
        throw new Error(`${filename} has unresolved relative ref: ${ref}`);
      }
    }
  }
}

export function generateAgentSchemas() {
  const schemas = readUpstreamSchemas();
  if (!schemas) {
    if (!existsSync(targetPath)) throw new Error("Upstream agent schemas are unavailable");
    return readFileSync(targetPath, "utf8");
  }
  const filenames = Object.keys(schemas).sort();
  if (filenames.length !== 23) {
    throw new Error(`Expected 23 agent schemas, found ${filenames.length}`);
  }
  validateSchemaRefs(schemas);
  const entries = filenames
    .map(
      (filename) => `  ${JSON.stringify(filename)}: ${JSON.stringify(schemas[filename], null, 2)},`,
    )
    .join("\n");
  return `// Generated by tools/codegen/agent-schemas.ts. Do not edit manually.

/** @typedef {Record<string, unknown>} AgentJsonSchema */

export const agentSchemaCount = ${filenames.length};
export const agentSchemaFilenames = Object.freeze(${JSON.stringify(filenames)});

/** @type {Readonly<Record<string, AgentJsonSchema>>} */
export const agentSchemas = Object.freeze({
${entries}
});
`;
}

export function writeAgentSchemas() {
  writeFileSync(targetPath, generateAgentSchemas(), "utf8");
  console.log("Generated 23 agent schemas");
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  writeAgentSchemas();
}
