import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
const sourcePath = join(repositoryRoot, "contracts-source", "openapi-v1.yaml");
const targetPath = join(repositoryRoot, "packages", "contracts", "src", "generated", "openapi.ts");
const source = readFileSync(sourcePath, "utf8");
const sourceHash = createHash("sha256").update(source).digest("hex").toUpperCase();
const operationIds = [...source.matchAll(/^\s+operationId:\s*([A-Za-z0-9_.-]+)\s*$/gm)].map(
  (match) => match[1],
);

if (operationIds.length !== 137) {
  throw new Error(`Expected 137 OpenAPI operations, found ${operationIds.length}`);
}

if (new Set(operationIds).size !== operationIds.length) {
  throw new Error("OpenAPI operation IDs must be unique");
}

const operationEntries = operationIds
  .map((operationId) => `  ${JSON.stringify(operationId)}: { request: undefined, response: undefined },`)
  .join("\n");
const generated = `// Generated by tools/codegen/openapi.ts. Do not edit manually.
// Source SHA-256: ${sourceHash}

/** @typedef {typeof openApiOperationIds[number]} OpenApiOperationId */
/** @typedef {{ request: unknown, response: unknown }} OpenApiOperationTypes */

export const openApiOperationIds = Object.freeze([
${operationIds.map((operationId) => `  ${JSON.stringify(operationId)},`).join("\n")}
]);

/** @type {Readonly<Record<OpenApiOperationId, OpenApiOperationTypes>>} */
export const openApiOperations = Object.freeze({
${operationEntries}
});

export const openApiOperationCount = ${operationIds.length};
`;

writeFileSync(targetPath, generated, "utf8");
console.log(`Generated ${operationIds.length} OpenAPI operations`);
