import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
const sourcePath = join(repositoryRoot, "contracts-source", "screen-data-contracts.yaml");
const targetPath = join(repositoryRoot, "packages", "contracts", "src", "generated", "screens.ts");

export function parseScreenContracts(source) {
  const ids = [...source.matchAll(/^- id:\s*([^\s]+)\s*$/gm)].map((match) => match[1]);
  const routes = [...source.matchAll(/^\s+route:\s*([^\s]+)\s*$/gm)].map((match) => match[1]);

  if (ids.length !== 29 || routes.length !== 29) {
    throw new Error(
      `Expected 29 screen contracts, found ${ids.length} IDs and ${routes.length} routes`,
    );
  }

  if (new Set(routes).size !== routes.length) {
    throw new Error("Screen contract routes must be unique");
  }

  return ids.map((id, index) => ({ id, route: routes[index] }));
}

export function generateScreens(source) {
  const screens = parseScreenContracts(source);
  const entries = screens
    .map(({ id, route }) => `  { id: ${JSON.stringify(id)}, route: ${JSON.stringify(route)} },`)
    .join("\n");
  return `// Generated by tools/codegen/screens.ts. Do not edit manually.

/** @typedef {{ id: string, route: string }} ScreenContract */

export const screenContracts = Object.freeze([
${entries}
]);

export const screenContractIds = Object.freeze(screenContracts.map(({ id }) => id));
export const screenContractCount = ${screens.length};
`;
}

export function writeScreens() {
  writeFileSync(targetPath, generateScreens(readFileSync(sourcePath, "utf8")), "utf8");
  console.log("Generated 29 screen contracts");
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  writeScreens();
}
