import type { FastifyPluginAsync } from "fastify";
import type { GenerationUseCases } from "../../../../../packages/core/src/modules/campaign/generation-use-cases.js";
import type { AsyncCommandPublisher } from "../../../../../packages/core/src/async/command-publisher.js";
import { actorReference, headerValue } from "../../async/route-policy.js";

interface Options { readonly generation: GenerationUseCases; readonly asyncCommands?: AsyncCommandPublisher }
interface Params { readonly workspaceId: string; readonly campaignId: string; readonly requestId?: string }
function params(request: unknown): Params { return (request as { params: Params }).params; }
function body(request: unknown): Record<string, unknown> { return ((request as { body?: unknown }).body ?? {}) as Record<string, unknown>; }

export const generationRoutes: FastifyPluginAsync<Options> = async (app, options) => {
  const { generation } = options;
app.post("/api/v1/workspaces/:workspaceId/campaigns/:campaignId/generation-requests", { config: { operationId: "createGenerationRequest", roles: ["OWNER", "ADMIN", "EDITOR"] } }, async (request, reply) => { const input = params(request); const value = body(request); const productIds = Array.isArray(value.productIds) ? value.productIds.map(String) : []; const formatSelectionIds = Array.isArray(value.formatSelectionIds) ? value.formatSelectionIds.map(String) : []; const variantCount = Math.max(1, Math.min(10, Number(value.variantCountPerProduct ?? 1))); if (options.asyncCommands) { const actor = actorReference(request); const idempotencyKey = headerValue(request, "idempotency-key"); const result = await options.asyncCommands.enqueue({ workspaceId: input.workspaceId, command: "creative.generate", schemaVersion: 1, payload: { campaignId: input.campaignId, productIds, formatProfileIds: formatSelectionIds, variantCountPerProduct: variantCount, generationMode: "MOCK_AI" as const }, ...(actor ? { requestedBy: actor } : {}), ...(idempotencyKey ? { idempotencyKey } : {}) }); const location = `/api/v1/workspaces/${input.workspaceId}/jobs/${result.jobId}`; reply.header("Operation-Location", location); reply.header("Location", location); reply.header("Retry-After", "3"); return reply.code(202).send({ job: { id: result.jobId, status: result.status }, links: { self: location } }); } const aggregate = await generation.create({ workspaceId: input.workspaceId, campaignId: input.campaignId, ...(value.briefVersionId ? { briefVersionId: String(value.briefVersionId) } : {}), products: productIds.map((productId) => ({ productId, variantKeys: Array.from({ length: variantCount }, (_, index) => `variant-${index + 1}`) })), formatProfileIds: formatSelectionIds }); const location = `/api/v1/workspaces/${input.workspaceId}/campaigns/${input.campaignId}/generation-requests/${aggregate.request.id}`; reply.header("Operation-Location", location); reply.header("Location", location); reply.header("Retry-After", "3"); return reply.code(202).send({ job: { id: aggregate.request.id, status: aggregate.request.status }, resource: aggregate.request, links: { self: location } }); });
  app.get("/api/v1/workspaces/:workspaceId/campaigns/:campaignId/generation-requests/:requestId", { config: { operationId: "getGenerationRequest" } }, async (request, reply) => { const input = params(request); const result = await generation.get(input.workspaceId, input.requestId!); if (!result || result.request.campaignId !== input.campaignId) return reply.code(404).send({ code: "RESOURCE_NOT_FOUND" }); return { data: result }; });
};
