import { randomUUID } from "node:crypto";
import type { FastifyPluginAsync } from "fastify";
import type { AssetUseCases } from "../../../../../packages/core/src/modules/asset/asset-use-cases.js";
import { etagForRevision, revisionFromEtag } from "../../concurrency/etag.js";

interface Options { readonly assets: AssetUseCases }
interface Params { readonly workspaceId: string; readonly brandId?: string; readonly assetId?: string; readonly versionId?: string }
function params(request: unknown): Params { return (request as { params: Params }).params; }
function body(request: unknown): Record<string, unknown> { return ((request as { body?: unknown }).body ?? {}) as Record<string, unknown>; }
function expected(request: unknown): number | undefined { const value = (request as { headers?: { "if-match"?: string } }).headers?.["if-match"]; return value ? revisionFromEtag(value) : undefined; }

export const assetRoutes: FastifyPluginAsync<Options> = async (app, { assets }) => {
  app.get("/api/v1/workspaces/:workspaceId/brands/:brandId/assets", { config: { operationId: "listAssets" } }, async (request) => { const input = params(request); return { items: await assets.list(input.workspaceId, input.brandId!) }; });
  app.post("/api/v1/workspaces/:workspaceId/brands/:brandId/assets", { config: { operationId: "createAsset", roles: ["OWNER", "ADMIN", "EDITOR"] } }, async (request, reply) => { const input = params(request); const value = body(request); const item = await assets.create({ workspaceId: input.workspaceId, brandId: input.brandId!, name: String(value.name), assetType: String(value.assetType ?? "IMAGE"), ...(value.licenseStatus ? { licenseStatus: String(value.licenseStatus) as never } : {}), ...(value.licenseStartAt ? { licenseStartAt: String(value.licenseStartAt) } : {}), ...(value.licenseEndAt ? { licenseEndAt: String(value.licenseEndAt) } : {}), ...(typeof value.analysisSummaryJson === "object" && value.analysisSummaryJson ? { analysisSummaryJson: value.analysisSummaryJson as Record<string, unknown> } : {}) }); reply.header("ETag", etagForRevision(item.revisionNo)); return reply.code(201).send({ data: item }); });
  app.get("/api/v1/workspaces/:workspaceId/assets/:assetId", { config: { operationId: "getAsset" } }, async (request, reply) => { const input = params(request); const item = await assets.get(input.workspaceId, input.assetId!); if (!item) return reply.code(404).send({ code: "RESOURCE_NOT_FOUND" }); reply.header("ETag", etagForRevision(item.revisionNo)); return { data: item }; });
  app.patch("/api/v1/workspaces/:workspaceId/assets/:assetId", { config: { operationId: "updateAsset", roles: ["OWNER", "ADMIN", "EDITOR"] } }, async (request, reply) => { const input = params(request); const item = await assets.update(input.workspaceId, input.assetId!, body(request) as never, expected(request)); reply.header("ETag", etagForRevision(item.revisionNo)); return { data: item }; });
  app.delete("/api/v1/workspaces/:workspaceId/assets/:assetId", { config: { operationId: "archiveAsset", roles: ["OWNER", "ADMIN", "EDITOR"] } }, async (request, reply) => { const input = params(request); await assets.archive(input.workspaceId, input.assetId!, expected(request)); return reply.code(204).send(); });
  app.get("/api/v1/workspaces/:workspaceId/assets/:assetId/versions", { config: { operationId: "listAssetVersions" } }, async (request) => { const input = params(request); return { items: await assets.listVersions(input.workspaceId, input.assetId!) }; });
  app.get("/api/v1/workspaces/:workspaceId/asset-versions/:versionId", { config: { operationId: "getAssetVersion" } }, async (request, reply) => { const input = params(request); const item = await assets.getVersion(input.workspaceId, input.versionId!); if (!item) return reply.code(404).send({ code: "RESOURCE_NOT_FOUND" }); return { data: item }; });
  app.post("/api/v1/workspaces/:workspaceId/assets/:assetId.analyze", { config: { operationId: "analyzeAsset", roles: ["OWNER", "ADMIN", "EDITOR"] } }, async (request, reply) => { const input = params(request); const jobId = randomUUID(); const location = `/api/v1/workspaces/${input.workspaceId}/jobs/${jobId}`; reply.header("Operation-Location", location); reply.header("Location", `/api/v1/workspaces/${input.workspaceId}/assets/${input.assetId}`); reply.header("Retry-After", "3"); return reply.code(202).send({ job: { id: jobId, status: "QUEUED" }, links: { self: location } }); });
  app.post("/api/v1/workspaces/:workspaceId/assets/:assetId.background-remove", { config: { operationId: "removeAssetBackground", roles: ["OWNER", "ADMIN", "EDITOR"] } }, async (request, reply) => { const input = params(request); const jobId = randomUUID(); const location = `/api/v1/workspaces/${input.workspaceId}/jobs/${jobId}`; reply.header("Operation-Location", location); reply.header("Location", `/api/v1/workspaces/${input.workspaceId}/assets/${input.assetId}`); reply.header("Retry-After", "3"); return reply.code(202).send({ job: { id: jobId, status: "QUEUED" }, links: { self: location } }); });
};
